on:
    push:
      branches:
        - "*"

jobs:
    app-build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: builds
          run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
        - name: Running jobs on
          run: echo "ğŸ§ This job is running on a ${{ runner.os }} server hosted by GitHub!"
        - name: Set up Node.js version
          uses: actions/setup-node@v1
          with:
            node-version: "20.x"
        - name: npm install, build, and test
          run: |
            npm install
            npm run build --omit=dev
            # npm run test â€” if-present
        - name: List files in the repository
          run: ls ${{ github.workspace }}
        - name: Show job status
          run: echo "ğŸŒŸ This job's status is ${{ job.status }}."